# Stub File for pyNetX.

from typing import Awaitable, Any

def set_threadpool_size(n: int) -> None: ...
def set_notification_reactor_count(n: int) -> None: ...
def next_notification_event(timeout_ms: int = -1) -> "NotificationHealthEvent": ...
def next_notification_event_async(timeout_ms: int = -1) -> Awaitable["NotificationHealthEvent"]: ...
def pending_notification_event_count() -> int: ...
def clear_notification_events() -> None: ...

class NetconfException(RuntimeError): ...
class NetconfConnectionRefusedError(ConnectionError): ...
class NetconfAuthError(PermissionError): ...
class NetconfChannelError(OSError): ...

class NotificationHealthEvent:
    valid: bool
    type: str
    timestamp: str
    label: str
    hostname: str
    port: int
    fd: int
    message: str
    queue_size: int
    queue_max_size: int
    queue_high_watermark: int
    notifications_enqueued: int
    notifications_dropped_queue_full: int
    notifications_dropped_delta: int
    incomplete_notifications_received: int
    partial_bytes: int
    health_events_dropped: int
    def as_dict(self) -> dict[str, Any]: ...

class NetconfClient:
    def __init__(
        self,
        hostname: str,
        *,
        port: int = 830,
        username: str,
        password: str,
        key_path: str = "",
        connect_timeout: int = 60,
        read_timeout: int = 60,
        notif_queue_size: int = -1,
        socket_connect_timeout: int = 5,
        notif_incomplete_max_kb: int = 1024,
        notif_incomplete_timeout: int = 5,
        notif_drop_event_threshold: int = 1,
        label: str = "None"
    ) -> None: ...
    # Synchronous methods
    # Deprecated since pyNetX 2.0.5.
    # These synchronous flow APIs will be removed in a future major release.
    # Use the corresponding *_async methods instead.
    def connect_sync(self) -> bool: ...
    def disconnect_sync(self) -> None: ...
    def delete_subscription(self) -> None: ...
    def send_rpc_sync(self, rpc: str) -> str: ...
    def receive_notification_sync(self) -> str: ...
    def get_sync(self, filter: str = "") -> str: ...
    def get_config_sync(self, source: str = "running", filter: str = "") -> str: ...
    def copy_config_sync(self, target: str, source: str) -> str: ...
    def delete_config_sync(self, target: str) -> str: ...
    def validate_sync(self, source: str = "running") -> str: ...
    def edit_config_sync(self, target: str, config: str, do_validate: bool = False) -> str: ...
    def subscribe_sync(self, stream: str = "NETCONF", filter: str = "") -> str: ...
    def lock_sync(self, target: str = "running") -> str: ...
    def unlock_sync(self, target: str = "running") -> str: ...
    def commit_sync(self) -> str: ...
    def locked_edit_config_sync(self, target: str, config: str, do_validate: bool = False) -> str: ...
    # Asynchronous methods
    def connect_async(self) -> Awaitable[bool]: ...
    def is_subscription_active(self) -> bool: ...
    def disconnect_async(self) -> Awaitable[None]: ...
    def send_rpc_async(self, rpc: str) -> Awaitable[str]: ...
    def next_notification(self, timeout_ms: int = 10) -> str: ...
    def next_notification_async(self, timeout_ms: int = 10) -> Awaitable[str]: ...
    def peek_notifications(self, max_items: int = 100) -> list[str]: ...
    def notification_queue_size(self) -> int: ...
    def get_async(self, filter: str = "") -> Awaitable[str]: ...
    def get_config_async(self, source: str = "running", filter: str = "") -> Awaitable[str]: ...
    def copy_config_async(self, target: str, source: str) -> Awaitable[str]: ...
    def delete_config_async(self, target: str) -> Awaitable[str]: ...
    def validate_async(self, source: str = "running") -> Awaitable[str]: ...
    def edit_config_async(self, target: str, config: str, do_validate: bool = False) -> Awaitable[str]: ...
    def subscribe_async(self, stream: str = "NETCONF", filter: str = "") -> Awaitable[str]: ...
    def lock_async(self, target: str = "running") -> Awaitable[str]: ...
    def unlock_async(self, target: str = "running") -> Awaitable[str]: ...
    def commit_async(self) -> Awaitable[str]: ...
    def locked_edit_config_async(self, target: str, config: str, do_validate: bool = False) -> Awaitable[str]: ...
